# XFS is not supported by GKE COS, use Ubuntu
# ref https://github.com/kubernetes/kubernetes/issues/47125
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ssd
  namespace: db
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
  #fsType: xfs
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: hdd
  namespace: db
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  #fsType: xfs
